name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag school-closing-api:latest

      - name: Run the Docker container
        run: |
          echo "PORT=$PORT"
          docker run -d \
            -p ${PORT}:${PORT} \
            -e PORT=${PORT} \
            -e HOST=${HOST} \
            -e CLOSING_DATA_1=${CLOSING_DATA_1} \
            --name school-closing-api \
            school-closing-api:latest
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          CLOSING_DATA_1: ${{ secrets.CLOSING_DATA_1 }}
