name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set environment variables
        run: echo "PORT=${{ secrets.PORT }}\nHOST=${{ secrets.HOST }}\nCLOSING_DATA_1=${{ secrets.CLOSING_DATA_1 }}" > .env
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Run the Docker container
        run: |
          docker run -d \
            -p ${PORT}:${PORT} \
            -e PORT=${PORT} \
            -e HOST=${HOST} \
            -e CLOSING_DATA_1=${CLOSING_DATA_1} \
            --name school-closing-api \
            my-image-name:latest
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          CLOSING_DATA_1: ${{ secrets.CLOSING_DATA_1 }}
