# This workflow will install dependencies, cache them, and run the server for the school-closing project

name: School Closing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create .env file
      run: echo "PORT=3023\nHOST=0.0.0.0\nCLOSING_DATA_1=your_data_url" > .env
    - run: npm ci
    - run: npm start
