# This workflow will install dependencies, cache them, and run the server for the school-closing project

name: School Closing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: Production
    env:
      PORT: ${{ secrets.PORT }}
      HOST: ${{ secrets.HOST }}
      CLOSING_DATA_1: ${{ secrets.CLOSING_DATA_1 }}

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Set environment variables
      run: echo "PORT=${{ secrets.PORT }}\nHOST=${{ secrets.HOST }}\nCLOSING_DATA_1=${{ secrets.CLOSING_DATA_1 }}" > .env
    - run: docker build . --file Dockerfile --tag school-closing-api:latest
    - run: |
        docker run -d \
          -p $PORT:$PORT \
          -e PORT=$PORT \
          -e HOST=$HOST \
          -e CLOSING_DATA_1=$CLOSING_DATA_1 \
          --name school-closing-api \
          school-closing-api:latest
